=== sixrobin/Febilis/Assets/Datafiles/Units/EnemiesDatas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

   <xs:include schemaLocation="../SharedDatas.xsd"/>
   <xs:include schemaLocation="AttacksDatas.xsd"/>

   <xs:element name="EnemiesDatas">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="EnemyDatas" minOccurs="0" maxOccurs="unbounded">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="Health" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>
                     <xs:element name="WalkSpeed" type="xs:float" minOccurs="1" maxOccurs="1"/>
                     <xs:element name="RunSpeed" type="xs:float" minOccurs="1" maxOccurs="1"/>
                     <xs:element name="HurtDur" type="xs:float" minOccurs="1" maxOccurs="1"/>
                     <xs:element name="PlayerDetectionDist" type="xs:float" minOccurs="1" maxOccurs="1"/>
                     <xs:element name="PlayerLoseDist" type="xs:float" minOccurs="1" maxOccurs="1"/>
                     <xs:element name="Physics" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="Jump" minOccurs="1" maxOccurs="1">
                                 <xs:complexType>
                                    <xs:sequence>
                                       <xs:element name="Height" minOccurs="1" maxOccurs="1"/>
                                       <xs:element name="ApexDur" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                 </xs:complexType>
                              </xs:element>
                              <xs:element name="HurtCheckEdge" minOccurs="1" maxOccurs="1"/>
                           </xs:sequence>
                        </xs:complexType>
                     </xs:element>
                     <xs:element name="Behaviours" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="Behaviour" minOccurs="1" maxOccurs="unbounded">
                                 <xs:complexType>
                                    <xs:sequence>
                                       <xs:element name="Conditions" type="Conditions" minOccurs="0" maxOccurs="1"/>
                                       <xs:element name="Actions" type="Actions" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                    <xs:attribute name="Name" type="xs:token" use="required"/>
                                 </xs:complexType>
                              </xs:element>
                           </xs:sequence>
                        </xs:complexType>
                     </xs:element>
                     <xs:element name="OnKilledTrauma" type="xs:float" minOccurs="0" maxOccurs="1"/>
                     <xs:element name="OnKilledLoot" type="LootDatas" minOccurs="0" maxOccurs="1"/>
                  </xs:sequence>
                  <xs:attribute name="Id" type="xs:token" use="required"/>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>



   <!-- ████████████ -->
   <!--  CONDITIONS  -->
   <!-- ████████████ -->

   <xs:complexType name="Conditions">
      <xs:sequence>
         <xs:element name="LastActionsCheck" type="LastActionsCheckCondition" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="FullHealth" type="FullHealthCondition" minOccurs="0" maxOccurs="1"/>
         <xs:element name="HealthCurrentMax" type="HealthCurrentCondition" minOccurs="0" maxOccurs="1"/>
         <xs:element name="HealthCurrentMin" type="HealthCurrentCondition" minOccurs="0" maxOccurs="1"/>
         <xs:element name="HealthPercentageMax" type="HealthPercentageCondition" minOccurs="0" maxOccurs="1"/>
         <xs:element name="HealthPercentageMin" type="HealthPercentageCondition" minOccurs="0" maxOccurs="1"/>
         <xs:element name="MaxHeightOffset" type="MaxHeightOffsetCondition" minOccurs="0" maxOccurs="1"/>
         <xs:element name="PlayerAbove" type="PlayerAboveCondition" minOccurs="0" maxOccurs="1"/>
         <xs:element name="PlayerAlive" type="PlayerAliveCondition" minOccurs="0" maxOccurs="1"/>
         <xs:element name="PlayerDetected" type="PlayerDetectedCondition" minOccurs="0" maxOccurs="1"/>
         <xs:element name="PlayerInRange" type="PlayerInRangeCondition" minOccurs="0" maxOccurs="1"/>
         <xs:element name="RandomChance" type="RandomChanceCondition" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="Condition">
      <xs:attribute name="Negate" type="xs:boolean" use="optional"/>
   </xs:complexType>

   <xs:complexType name="FullHealthCondition">
      <xs:complexContent>
         <xs:extension base="Condition"/>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="HealthCurrentCondition">
      <xs:complexContent>
         <xs:extension base="Condition">
            <xs:attribute name="Threshold" type="xs:positiveInteger" use="required"/>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="HealthPercentageCondition">
      <xs:complexContent>
         <xs:extension base="Condition">
            <xs:attribute name="Threshold" type="xs:float" use="required"/>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="LastActionsCheckCondition">
      <xs:complexContent>
         <xs:extension base="Condition">
            <xs:sequence>
               <xs:element name="Include" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
               <xs:element name="Exclude" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="ActionsCount" type="xs:positiveInteger" use="required"/>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="MaxHeightOffsetCondition">
      <xs:complexContent>
         <xs:extension base="Condition">
            <xs:attribute name="Offset" type="xs:float" use="required"/>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="PlayerAboveCondition">
      <xs:complexContent>
         <xs:extension base="Condition"/>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="PlayerAliveCondition">
      <xs:complexContent>
         <xs:extension base="Condition"/>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="PlayerDetectedCondition">
      <xs:complexContent>
         <xs:extension base="Condition"/>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="PlayerInRangeCondition">
      <xs:complexContent>
         <xs:extension base="Condition">
            <xs:attribute name="Range" type="xs:float" use="required"/>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="RandomChanceCondition">
      <xs:complexContent>
         <xs:extension base="Condition">
            <xs:attribute name="Chance" type="xs:float" use="required"/>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>



   <!-- ███████████ -->
   <!--   ACTIONS   -->
   <!-- ███████████ -->

   <xs:complexType name="Actions">
      <xs:choice maxOccurs="unbounded">
         <xs:element name="Attack" type="AttackAction" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="BackAndForth" type="BackAndForthAction" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="Charge" type="ChargeAction" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="Chase" type="ChaseAction" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="Flee" type="FleeAction" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="Wait" type="WaitAction" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
   </xs:complexType>

   <xs:complexType name="Action">
      <xs:sequence>
         <xs:element name="Conditions" type="Conditions" minOccurs="0" maxOccurs="1"/>
         <xs:element name="CantBeHurt" minOccurs="0" maxOccurs="1"/>
         <xs:element name="DontApplyGravity" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="AttackAction">
      <xs:complexContent>
         <xs:extension base="Action">
            <xs:sequence>
               <xs:element name="Delay" minOccurs="0" maxOccurs="1">
                  <xs:complexType>
                     <xs:attribute name="Min" type="xs:float" use="required"/>
                     <xs:attribute name="Max" type="xs:float" use="required"/>
                  </xs:complexType>
               </xs:element>
               <xs:element name="AnimatorId" type="xs:token" minOccurs="1" maxOccurs="1"/>
               <xs:element name="AnimatorEnemyIdOverride" type="xs:token" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="Id" type="xs:token" use="required"/>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="BackAndForthAction">
      <xs:complexContent>
         <xs:extension base="Action">
            <xs:sequence>
               <xs:element name="Range" type="xs:float" minOccurs="1" maxOccurs="1"/>
               <xs:element name="Pause" minOccurs="0" maxOccurs="1">
                  <xs:complexType>
                     <xs:attribute name="Min" type="xs:float" use="required"/>
                     <xs:attribute name="Max" type="xs:float" use="required"/>
                  </xs:complexType>
               </xs:element>
               <xs:element name="RangeFluctuationOnPause" type="xs:float" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="ChargeAction">
      <xs:complexContent>
         <xs:extension base="Action">
            <xs:sequence>
               <xs:element name="AnticipationDuration" type="xs:float" minOccurs="1" maxOccurs="1"/>
               <xs:element name="InitSpeed" type="xs:float" minOccurs="1" maxOccurs="1"/>
               <xs:element name="Acceleration" type="xs:float" minOccurs="1" maxOccurs="1"/>
               <xs:element name="MaxDuration" type="xs:float" minOccurs="0" maxOccurs="1"/>
               <xs:element name="PlayerCollision" type="ChargeCollision" minOccurs="0" maxOccurs="1"/>
               <xs:element name="WallCollision" type="ChargeCollision" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="ChargeCollision">
      <xs:sequence>
         <xs:element name="AttackId" type="xs:token" minOccurs="0" maxOccurs="1"/>
         <xs:element name="Stun" minOccurs="0" maxOccurs="1">
            <xs:complexType>
               <xs:attribute name="Dur" type="xs:float" use="required"/>
               <xs:attribute name="Delay" type="xs:float" use="optional"/>
            </xs:complexType>
         </xs:element>
         <xs:element name="CantSuicide" minOccurs="0" maxOccurs="1"/>
         <xs:element name="Trauma" type="TraumaDatas" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="ChaseAction">
      <xs:complexContent>
         <xs:extension base="Action"/>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="FleeAction">
      <xs:complexContent>
         <xs:extension base="Action">
            <xs:sequence>
               <xs:element name="FacePlayer" minOccurs="0" maxOccurs="1"/>
               <xs:element name="WalkAnimationMultiplier" type="xs:float" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="WaitAction">
      <xs:complexContent>
         <xs:extension base="Action">
            <xs:sequence>
               <xs:element name="FacePlayer" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

</xs:schema>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Units/EnemiesDatas.xml
<?xml version="1.0" encoding="utf-8" ?>
<EnemiesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EnemiesDatas.xsd">
   
   <EnemyDatas Id="Skeleton">
      <Health>150</Health>
      <WalkSpeed>1.3</WalkSpeed>
      <RunSpeed>3</RunSpeed>
      <HurtDur>0.25</HurtDur>
      <PlayerDetectionDist>3.5</PlayerDetectionDist>
      <PlayerLoseDist>5</PlayerLoseDist>
      <Physics>
         <Jump>
            <Height>2</Height>
            <ApexDur>0.3</ApexDur>
         </Jump>
         <HurtCheckEdge>true</HurtCheckEdge>
      </Physics>
      <Behaviours>
         <!--<Behaviour Name="Flee">
            <Conditions>
               <HealthMax Threshold="140"/>
               <PlayerDetected/>
            </Conditions>
            <Actions>
               <Flee>
                  <FacePlayer>true</FacePlayer>
               </Flee>
            </Actions>
         </Behaviour>-->
         <Behaviour Name="ChargeTest">
            <Conditions>
               <PlayerDetected/>
            </Conditions>
            <Actions>
               <Charge>
                  <!--<CantBeHurt/>-->
                  <!--<MaxDuration>3</MaxDuration>-->
               </Charge>
            </Actions>
         </Behaviour>
         <Behaviour Name="Base">
            <Actions>
               <Attack Id="skeleton_atk_above">
                  <Conditions>
                     <PlayerAbove/>
                     <PlayerAlive/>
                  </Conditions>
                  <AnimatorId>Above</AnimatorId>
               </Attack>
               <Attack Id="skeleton_atk_base">
                  <Conditions>
                     <PlayerAlive/>
                     <PlayerInRange Range="2.5"/>
                  </Conditions>
                  <Delay Min="0.45" Max="0.55"/>
                  <AnimatorId>Base</AnimatorId>
               </Attack>
               <Chase>
                  <Conditions>
                     <MaxHeightOffset Offset="0.2"/>
                     <PlayerAlive/>
                     <PlayerDetected/>
                  </Conditions>
               </Chase>
               <BackAndForth>
                  <Range>2.5</Range>
                  <Pause Min="0.5" Max="1.5"/>
                  <RangeFluctuationOnPause>1.5</RangeFluctuationOnPause>
               </BackAndForth>
            </Actions>
         </Behaviour>
      </Behaviours>
      <!--<EventBehaviours>
         --><!--Just some event ideas.--><!--
         <OnHurtOver/>
         <OnAttackHit/>
         <OnPlayerDeath/>
      </EventBehaviours>-->
      <OnKilledTrauma>0.4</OnKilledTrauma>
      <OnKilledLoot>
         <Coins>5</Coins>
      </OnKilledLoot>
   </EnemyDatas>

   <EnemyDatas Id="Rat">
      <Health>60</Health>
      <WalkSpeed>3.5</WalkSpeed>
      <RunSpeed>6</RunSpeed>
      <HurtDur>0.15</HurtDur>
      <PlayerDetectionDist>4</PlayerDetectionDist>
      <PlayerLoseDist>10</PlayerLoseDist>
      <Physics>
         <Jump>
            <Height>2</Height>
            <ApexDur>0.3</ApexDur>
         </Jump>
         <HurtCheckEdge>true</HurtCheckEdge>
      </Physics>
      <Behaviours>
         <Behaviour Name="Base">
            <Actions>
               <Attack Id="rat_atk_base">
                  <Conditions>
                     <PlayerAlive/>
                     <PlayerInRange Range="1.5"/>
                  </Conditions>
                  <Delay Min="0.3" Max="0.4"/>
                  <AnimatorId>Base</AnimatorId>
               </Attack>
               <Chase>
                  <Conditions>
                     <MaxHeightOffset Offset="0.5"/>
                     <PlayerDetected/>
                  </Conditions>
               </Chase>
               <BackAndForth>
                  <Range>3</Range>
                  <Pause Min="0.2" Max="0.5"/>
                  <!--Make the range random between 2 and 8, but always from the same origin point.-->
                  <RangeFluctuationOnPause>2</RangeFluctuationOnPause>
               </BackAndForth>
            </Actions>
         </Behaviour>
      </Behaviours>
      <OnKilledLoot>
         <Coins>2</Coins>
      </OnKilledLoot>
   </EnemyDatas>

   <EnemyDatas Id="EnragedRat">
      <Health>60</Health>
      <WalkSpeed>3.5</WalkSpeed>
      <RunSpeed>6</RunSpeed>
      <HurtDur>0.15</HurtDur>
      <PlayerDetectionDist>4</PlayerDetectionDist>
      <PlayerLoseDist>10</PlayerLoseDist>
      <Physics>
         <Jump>
            <Height>2</Height>
            <ApexDur>0.3</ApexDur>
         </Jump>
         <HurtCheckEdge>true</HurtCheckEdge>
      </Physics>
      <Behaviours>
         <Behaviour Name="Base">
            <Actions>
               <Attack Id="rat_atk_base">
                  <Conditions>
                     <PlayerAlive/>
                     <PlayerInRange Range="1.5"/>
                  </Conditions>
                  <Delay Min="0.3" Max="0.4"/>
                  <AnimatorId>Base</AnimatorId>
                  <AnimatorEnemyIdOverride>Rat</AnimatorEnemyIdOverride>
               </Attack>
               <Chase>
                  <Conditions>
                     <MaxHeightOffset Offset="0.5"/>
                     <PlayerDetected/>
                  </Conditions>
               </Chase>
               <BackAndForth>
                  <Range>3</Range>
                  <Pause Min="0.2" Max="0.5"/>
                  <!--Make the range random between 2 and 8, but always from the same origin point.-->
                  <RangeFluctuationOnPause>2</RangeFluctuationOnPause>
               </BackAndForth>
            </Actions>
         </Behaviour>
      </Behaviours>
      <OnKilledLoot>
         <Coins>2</Coins>
      </OnKilledLoot>
   </EnemyDatas>
   
</EnemiesDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Units/EnemiesDatas_RatKing.xml
<?xml version="1.0" encoding="utf-8" ?>
<EnemiesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EnemiesDatas.xsd">

   <EnemyDatas Id="RatKing">
      <Health>1000</Health>
      <WalkSpeed>4</WalkSpeed>
      <RunSpeed>8</RunSpeed>
      <HurtDur>0.3</HurtDur>
      <PlayerDetectionDist>4</PlayerDetectionDist>
      <PlayerLoseDist>-1</PlayerLoseDist>
      <Physics>
         <Jump>
            <Height>2</Height>
            <ApexDur>0.3</ApexDur>
         </Jump>
         <HurtCheckEdge>true</HurtCheckEdge>
      </Physics>
      <Behaviours>
         <Behaviour Name="Phase1">
            <Conditions>
               <HealthPercentageMin Threshold="0.66"/>
               <PlayerAlive/>
               <PlayerDetected/>
            </Conditions>
            <Actions>
               <!--TODO: Attack if last action is a charge.-->
               <Charge>
                  <Conditions>
                     <LastActionsCheck ActionsCount="1">
                        <Exclude>Charge</Exclude>
                     </LastActionsCheck>
                     <PlayerInRange Range="4"/>
                  </Conditions>
                  <CantBeHurt/>
                  <AnticipationDuration>0.9</AnticipationDuration>
                  <InitSpeed>6</InitSpeed>
                  <Acceleration>3</Acceleration>
                  <PlayerCollision>
                     <AttackId>rat_king_charge</AttackId>
                     <Trauma X="0.4" Y="0.4" AddType="OVERRIDE" ShakeId="Medium"/>
                  </PlayerCollision>
                  <WallCollision>
                     <AttackId>rat_king_charge_self_stun</AttackId>
                     <Stun Dur="2" Delay="0.5"/>
                     <Trauma X="0.5" Y="0.5" AddType="OVERRIDE" CanShakeWhenOffscreen="true" ShakeId="Medium"/>
                  </WallCollision>
               </Charge>
               <Chase>
                  <!--Not in charge range: approach.-->
               </Chase>
            </Actions>
         </Behaviour>
         <Behaviour Name="Phase2">
            <Conditions>
               <HealthPercentageMin Threshold="0.3"/>
               <PlayerAlive/>
               <PlayerDetected/>
            </Conditions>
            <Actions>
               <Chase>
                  <Conditions>
                     <MaxHeightOffset Offset="0.2"/>
                     <PlayerAlive/>
                     <PlayerDetected/>
                  </Conditions>
               </Chase>
            </Actions>
         </Behaviour>
         <Behaviour Name="Phase3">
            <Conditions>
               <PlayerAlive/>
               <PlayerDetected/>
            </Conditions>
            <Actions>
               <Flee>
                  <FacePlayer/>
               </Flee>
            </Actions>
         </Behaviour>
         <Behaviour Name="PreFight">
            <Actions>
               <Wait>
                  <FacePlayer/>
               </Wait>
            </Actions>
         </Behaviour>
      </Behaviours>
      <!--<EventBehaviours>
         Just some event ideas.
         <OnHurtOver/>
         <OnAttackHit/>
         <OnPlayerDeath/>
      </EventBehaviours>-->
      <OnKilledTrauma>0.4</OnKilledTrauma>
      <OnKilledLoot>
         <Coins>5</Coins>
      </OnKilledLoot>
   </EnemyDatas>

</EnemiesDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/EnemiesDatas.xml
<?xml version="1.0" encoding="utf-8" ?>
<EnemiesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EnemiesDatas.xsd">
   
   <EnemyDatas Id="Skeleton">
      <Health>200</Health>
      <WalkSpeed>1.3</WalkSpeed>
      <RunSpeed>3</RunSpeed>
      <HurtDur>0.25</HurtDur>
      <PlayerDetectionDist>3.5</PlayerDetectionDist>
      <PlayerLoseDist>4.5</PlayerLoseDist>
      <!--Behaviours in order priority.-->
      <Behaviours>
         <Behaviour Name="Base">
            <!--<Conditions>
               --><!--Behaviours only run at 10% health or MORE.--><!--
               <HealthMin Threshold="10"/>
            </Conditions>-->
            <!--Actions in order priority : the first being validated will be used.-->
            <Actions>
               <Attack Id="skeleton_atk_base">
                  <Conditions>
                     <PlayerAlive/>
                     <PlayerInRange Range="2.5"/>
                  </Conditions>
                  <Delay Min="0.5" Max="0.6"/>
                  <!--<AnimatorSuffix> ??-->
               </Attack>

               <!--<Attack Id="skeleton_atk_above">
                  <Conditions>
                     <PlayerAbove/>
                  </Conditions>
               </Attack>-->

               <BackAndForth>
                  <Range>2.5</Range>
                  <Pause Min="0.5" Max="1.5"/>
                  <RangeFluctuationOnPause>1.5</RangeFluctuationOnPause>
               </BackAndForth>
            </Actions>
         </Behaviour>
      </Behaviours>
      <!--<EventBehaviours>
         --><!--Just some event ideas.--><!--
         <OnHurtOver/>
         <OnAttackHit/>
         <OnPlayerDeath/>
      </EventBehaviours>-->
      <OnKilledTrauma>0.4</OnKilledTrauma>
   </EnemyDatas>

   <!--<EnemyDatas Id="Rat">
      <Health>30</Health>
      <WalkSpeed>3.5</WalkSpeed>
      <RunSpeed>8</RunSpeed>
      <HurtDur>0.3</HurtDur>
      <PlayerDetectionDist>5</PlayerDetectionDist>
      <PlayerLoseDist>10</PlayerLoseDist>
      <Behaviours>
         <Behaviour Name="FullHealth">
            <Conditions>
               <FullHealth/>
            </Conditions>
            <Actions>
               <BackAndForth>
                  <Range>5</Range>
                  <Pause Min="0.5" Max="1.5"/>
                  --><!--Make the range random between 2 and 8, but always from the same origin point.--><!--
                  <RangeFluctuationOnPause>3</RangeFluctuationOnPause>
               </BackAndForth>
            </Actions>
         </Behaviour>
         <Behaviour Name="Flee">
            <Actions>
               <Flee/>
            </Actions>
         </Behaviour>
      </Behaviours>
   </EnemyDatas>-->
   
</EnemiesDatas>
