=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/AttacksDatas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

   <xs:element name="AttacksDatas">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="PlayerAttack" type="PlayerAttackDatas" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="EnemyAttack"  type="EnemyAttackDatas" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:complexType name="AttackDatas">
      <xs:sequence>
         <xs:element name="Dmg" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>
         <xs:element name="Hit" type="HitDatas" minOccurs="1" maxOccurs="1"/>
         <xs:element name="Unstoppable" minOccurs="0" maxOccurs="1"/>
         <xs:element name="ForceHurt" minOccurs="0" maxOccurs="1"/>
         <xs:element name="Recoil" type="RecoilDatas" minOccurs="1" maxOccurs="1"/>
         <xs:element name="Traumas" type="TraumasDatas" minOccurs="1" maxOccurs="1"/>
         <xs:element name="AnimSpeedMult" type="xs:float" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="Id" type="xs:token" use="required"/>
   </xs:complexType>

   <xs:complexType name="PlayerAttackDatas">
      <xs:complexContent>
         <xs:extension base="AttackDatas">
            <xs:sequence>
               <xs:element name="Dur" type="xs:float" minOccurs="1" maxOccurs="1"/>
               <xs:element name="ChainAllowedTime" type="xs:float" minOccurs="0" maxOccurs="1"/>
               <xs:element name="ControlVelocity" minOccurs="0" maxOccurs="1">
                  <xs:complexType>
                     <xs:sequence>
                        <xs:element name="MoveSpeed" type="xs:float" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="Gravity" type="xs:float" minOccurs="1" maxOccurs="1"/>
                     </xs:sequence>
                  </xs:complexType>
               </xs:element>
               <xs:element name="OverrideMotionVFXId" type="xs:token" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="EnemyAttackDatas">
      <xs:complexContent>
         <xs:extension base="AttackDatas">
            <xs:sequence>
               <xs:element name="ClipsDurations" minOccurs="0" maxOccurs="1">
                  <xs:complexType>
                     <xs:sequence>
                        <xs:element name="Anticipation" type="xs:float" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="Attack" type="xs:float" minOccurs="1" maxOccurs="1"/>
                     </xs:sequence>
                  </xs:complexType>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   
   
   
   <!-- █████████████ -->
   <!--   HIT DATAS   -->
   <!-- █████████████ -->

   <xs:complexType name="HitDatas">
      <xs:sequence>
         <xs:element name="Delay" type="xs:float" minOccurs="0" maxOccurs="1"/>
         <xs:element name="Dur" type="xs:float" minOccurs="1" maxOccurs="1"/>
         <xs:element name="Layer" type="HitLayer" minOccurs="1" maxOccurs="1"/>
         <xs:element name="DirComputationType" type="HitDirComputationType" minOccurs="0" maxOccurs="1"/>
         <xs:element name="FreezeFrameDur" type="xs:float" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>

   <xs:simpleType name="HitLayer" final="restriction">
      <xs:restriction base="xs:string">
         <xs:enumeration value="ALL"/>
         <xs:enumeration value="PLAYER"/>
         <xs:enumeration value="ENEMY"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="HitDirComputationType" final="restriction">
      <xs:restriction base="xs:string">
         <xs:enumeration value="ATTACK_DIR"/>
         <xs:enumeration value="X_OFFSET"/>
      </xs:restriction>
   </xs:simpleType>


   
   <!-- ██████████████ -->
   <!--  SHAKE TRAUMA  -->
   <!-- ██████████████ -->

   <xs:complexType name="TraumasDatas">
      <xs:sequence>
         <xs:element name="Base" type="TraumaDatas" minOccurs="0" maxOccurs="1"/>
         <xs:element name="Hit" type="TraumaDatas" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="TraumaDatas">
      <xs:attribute name="X" type="xs:float" use="required"/>
      <xs:attribute name="Y" type="xs:float" use="required"/>
      <xs:attribute name="AddType" type="TraumaAddType" use="required"/>
      <xs:attribute name="ShakeId" type="xs:token" use="optional"/>
   </xs:complexType>

   <xs:simpleType name="TraumaAddType" final="restriction">
      <xs:restriction base="xs:string">
         <xs:enumeration value="ADDITIVE"/>
         <xs:enumeration value="OVERRIDE"/>
      </xs:restriction>
   </xs:simpleType>



   <xs:complexType name="RecoilDatas">
      <xs:sequence>
         <xs:element name="Force" type="xs:float" minOccurs="1" maxOccurs="1"/>
         <xs:element name="Dur" type="xs:float" minOccurs="1" maxOccurs="1"/>
         <xs:element name="AirborneMult" type="xs:float" minOccurs="0" maxOccurs="1"/>
         <xs:element name="CheckEdge" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
   
</xs:schema>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/AttacksDatas_Enemies.xml
<?xml version="1.0" encoding="utf-8" ?>
<AttacksDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AttacksDatas.xsd">

   <!-- ████████████ -->
   <!--   SKELETON   -->
   <!-- ████████████ -->
   
   <EnemyAttack Id="skeleton_atk_base">
      <Dmg>25</Dmg>
      <Hit>
         <Dur>0.1</Dur>
         <Layer>PLAYER</Layer>
         <DirComputationType>ATTACK_DIR</DirComputationType>
         <FreezeFrameDur>0.07</FreezeFrameDur>
      </Hit>
      <Traumas>
         <Base X="0.25" Y="0.5" AddType="ADDITIVE"/>
         <Hit X="0.75" Y="0.75" AddType="OVERRIDE"/>
      </Traumas>
      <ClipsDurations>
         <Anticipation>0.5</Anticipation>
         <Attack>0.5</Attack>
      </ClipsDurations>
   </EnemyAttack>

   <EnemyAttack Id="skeleton_atk_above">
      <Dmg>15</Dmg>
      <Hit>
         <Dur>0.1</Dur>
         <Layer>PLAYER</Layer>
         <DirComputationType>X_OFFSET</DirComputationType>
         <FreezeFrameDur>0.07</FreezeFrameDur>
      </Hit>
      <Traumas>
         <Base X="0.25" Y="0.25" AddType="ADDITIVE"/>
         <Hit X="0.6" Y="0.6" AddType="OVERRIDE"/>
      </Traumas>
      <ClipsDurations>
         <Anticipation>0.4</Anticipation>
         <Attack>0.5</Attack>
      </ClipsDurations>
   </EnemyAttack>


   
   <!-- █████████ -->
   <!--    RAT    -->
   <!-- █████████ -->

   <EnemyAttack Id="rat_atk_base">
      <Dmg>10</Dmg>
      <Hit>
         <Dur>0.1</Dur>
         <Layer>PLAYER</Layer>
         <DirComputationType>ATTACK_DIR</DirComputationType>
         <FreezeFrameDur>0.05</FreezeFrameDur>
      </Hit>
      <Traumas>
         <Hit X="0.45" Y="0.45" AddType="OVERRIDE"/>
      </Traumas>
      <ClipsDurations>
         <Anticipation>0.33</Anticipation>
         <Attack>0.33</Attack>
      </ClipsDurations>
   </EnemyAttack>
   
</AttacksDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/AttacksDatas.xml
<?xml version="1.0" encoding="utf-8" ?>
<AttacksDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AttacksDatas.xsd">

   <!-- ██████████ -->
   <!--   PLAYER   -->
   <!-- ██████████ -->

   <Combo Id="base_combo">
      <Attack>atk_base_00</Attack>
      <Attack>atk_base_01</Attack>
      <Attack>atk_base_02</Attack>
   </Combo>
   
   <AttackDatas Id="atk_base_00">
      <Dmg>25</Dmg>
      <Dur>0.55</Dur>
      <Hit>
         <Dur>0.1</Dur>
         <Layer>ENEMY</Layer>
         <DirComputationType>ATTACK_DIR</DirComputationType>
         <FreezeFrameDur>0.1</FreezeFrameDur>
      </Hit>
      <ChainAllowedTime>0.48</ChainAllowedTime>
      <ControlVelocity>
         <MoveSpeed>1.7</MoveSpeed>
         <Gravity>0.5</Gravity>
         <!--Move speed curve ? Id link to some curves database ?-->
      </ControlVelocity>
      <Traumas>
         <Base X="0.1" Y="0.1" Type="Additive"/>
         <OnHit X="0.75" Y="0.75" Type="Override"/>
      </Traumas>
      <AnimSpeedMult>1</AnimSpeedMult>
   </AttackDatas>
   
   


   <!-- ███████████ -->
   <!--   ENEMIES   -->
   <!-- ███████████ -->
   
   <AttackDatas Id="skeleton_atk_base">
      <Dmg>15</Dmg>
      <ClipsDurations>
         <Anticipation>0.5</Anticipation>
         <Attack>0.5</Attack>
      </ClipsDurations>
      <Hit>
         <Dur>0.1</Dur>
         <Layer>PLAYER</Layer>
         <DirComputationType>ATTACK_DIR</DirComputationType>
         <FreezeFrameDur>0.1</FreezeFrameDur>
      </Hit>
      <Traumas>
         <Base X="0.1" Y="0.1" Type="Additive"/>
         <OnHit X="0.75" Y="0.75" Type="Override"/>
      </Traumas>
   </AttackDatas>
   
</AttacksDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/AttacksDatas_Player.xml
<?xml version="1.0" encoding="utf-8" ?>
<AttacksDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AttacksDatas.xsd">

   <PlayerAttack Id="atk_base_00">
      <Dmg>25</Dmg>
      <Hit>
         <Dur>0.25</Dur>
         <Layer>ENEMY</Layer>
         <DirComputationType>ATTACK_DIR</DirComputationType>
         <FreezeFrameDur>0.05</FreezeFrameDur>
      </Hit>
      <Traumas>
         <Hit X="0.25" Y="0.25" AddType="ADDITIVE"/>
      </Traumas>
      <Dur>0.55</Dur>
      <ChainAllowedTime>0.48</ChainAllowedTime>
      <ControlVelocity>
         <MoveSpeed>1.7</MoveSpeed>
         <Gravity>0.5</Gravity>
         <!--Move speed curve ? Id link to some curves database ?-->
      </ControlVelocity>
   </PlayerAttack>

   <PlayerAttack Id="atk_base_01">
      <Dmg>25</Dmg>
      <Hit>
         <Dur>0.25</Dur>
         <Layer>ENEMY</Layer>
         <DirComputationType>ATTACK_DIR</DirComputationType>
         <FreezeFrameDur>0.05</FreezeFrameDur>
      </Hit>
      <Traumas>
         <Hit X="0.25" Y="0.25" AddType="ADDITIVE"/>
      </Traumas>
      <Dur>0.55</Dur>
      <ChainAllowedTime>0.48</ChainAllowedTime>
      <ControlVelocity>
         <MoveSpeed>1.7</MoveSpeed>
         <Gravity>0.5</Gravity>
         <!--Move speed curve ? Id link to some curves database ?-->
      </ControlVelocity>
   </PlayerAttack>

   <PlayerAttack Id="atk_base_02">
      <Dmg>25</Dmg>
      <Hit>
         <Dur>0.25</Dur>
         <Layer>ENEMY</Layer>
         <DirComputationType>ATTACK_DIR</DirComputationType>
         <FreezeFrameDur>0.05</FreezeFrameDur>
      </Hit>
      <Traumas>
         <Hit X="0.25" Y="0.25" AddType="ADDITIVE"/>
      </Traumas>
      <Dur>0.55</Dur>
      <ControlVelocity>
         <MoveSpeed>2.5</MoveSpeed>
         <Gravity>0.5</Gravity>
         <!--Move speed curve ? Id link to some curves database ?-->
      </ControlVelocity>
   </PlayerAttack>

   <PlayerAttack Id="atk_airborne">
      <Dmg>25</Dmg>
      <Hit>
         <Dur>0.25</Dur>
         <Layer>ENEMY</Layer>
         <DirComputationType>ATTACK_DIR</DirComputationType>
         <FreezeFrameDur>0.05</FreezeFrameDur>
      </Hit>
      <Traumas>
         <Hit X="0.25" Y="0.25" AddType="ADDITIVE"/>
      </Traumas>
      <AnimSpeedMult>1.2</AnimSpeedMult>
      <Dur>0.4</Dur>
      <!--<ControlVelocity>
         <MoveSpeed>5</MoveSpeed>
         <Gravity>0.05</Gravity>
      </ControlVelocity>-->
   </PlayerAttack>
   
</AttacksDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Units/AttacksDatas_Enemies.xml
<?xml version="1.0" encoding="utf-8" ?>
<AttacksDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AttacksDatas.xsd">   

   <!-- ████████████ -->
   <!--   SKELETON   -->
   <!-- ████████████ -->
   
   <EnemyAttack Id="skeleton_atk_base">
      <Dmg>40</Dmg>
      <Hit>
         <Dur>0.1</Dur>
         <Layers>
            <LayerName>PLAYER</LayerName>
         </Layers>
         <DirComputationType>ATTACK_DIR</DirComputationType>
         <FreezeFrameDur>0.07</FreezeFrameDur>
      </Hit>
      <Recoil>
         <Force>7</Force>
         <Dur>0.25</Dur>
         <AirborneMult>2</AirborneMult>
      </Recoil>
      <Traumas>
         <Base X="0.25" Y="0.5" AddType="ADDITIVE" ShakeId="Small"/>
         <Hit X="0.75" Y="0.75" AddType="OVERRIDE" ShakeId="Big"/>
      </Traumas>
      <ClipsDurations>
         <Anticipation>0.5</Anticipation>
         <Attack>0.5</Attack>
      </ClipsDurations>
   </EnemyAttack>

   <EnemyAttack Id="skeleton_atk_above">
      <Dmg>30</Dmg>
      <Hit>
         <Dur>0.1</Dur>
         <Layers>
            <LayerName>PLAYER</LayerName>
         </Layers>
         <DirComputationType>X_OFFSET</DirComputationType>
         <FreezeFrameDur>0.07</FreezeFrameDur>
      </Hit>
      <Recoil>
         <Force>9</Force>
         <Dur>0.3</Dur>
         <AirborneMult>1.5</AirborneMult>
      </Recoil>
      <Traumas>
         <Base X="0.25" Y="0.25" AddType="ADDITIVE" ShakeId="Small"/>
         <Hit X="0.6" Y="0.6" AddType="OVERRIDE" ShakeId="Medium"/>
      </Traumas>
      <ClipsDurations>
         <Anticipation>0.4</Anticipation>
         <Attack>0.5</Attack>
      </ClipsDurations>
   </EnemyAttack>


   
   <!-- █████████ -->
   <!--    RAT    -->
   <!-- █████████ -->

   <EnemyAttack Id="rat_atk_base">
      <Dmg>25</Dmg>
      <Hit>
         <Dur>0.1</Dur>
         <Layers>
            <LayerName>PLAYER</LayerName>
         </Layers>
         <DirComputationType>ATTACK_DIR</DirComputationType>
         <FreezeFrameDur>0.05</FreezeFrameDur>
      </Hit>
      <Recoil>
         <Force>7</Force>
         <Dur>0.25</Dur>
         <AirborneMult>1</AirborneMult>
      </Recoil>
      <Traumas>
         <Hit X="0.45" Y="0.45" AddType="OVERRIDE" ShakeId="Small"/>
      </Traumas>
      <ClipsDurations>
         <Anticipation>0.33</Anticipation>
         <Attack>0.33</Attack>
      </ClipsDurations>
   </EnemyAttack>



   <!-- ████████ -->
   <!-- RAT KING -->
   <!-- ████████ -->

   <EnemyAttack Id="rat_king_charge">
      <Dmg>40</Dmg>
      <Hit>
         <Dur>0.1</Dur>
         <Layers>
            <LayerName>PLAYER</LayerName>
         </Layers>
         <DirComputationType>ATTACK_DIR</DirComputationType>
         <FreezeFrameDur>0.1</FreezeFrameDur>
      </Hit>
      <ForceHurt/>
      <Recoil>
         <Force>9</Force>
         <Dur>0.35</Dur>
         <AirborneMult>1</AirborneMult>
      </Recoil>
   </EnemyAttack>
   
   <EnemyAttack Id="rat_king_charge_self_stun">
      <Dmg>5</Dmg>
      <Hit>
         <Dur>0.1</Dur>
         <Layers>
            <LayerName>ENEMY</LayerName>
         </Layers>
         <DirComputationType>ATTACK_DIR</DirComputationType>
         <FreezeFrameDur>0</FreezeFrameDur>
      </Hit>
   </EnemyAttack>
   
</AttacksDatas>
