=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/DestroyablesDatas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

   <xs:element name="DestroyablesDatas">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="DestroyableDatas" minOccurs="0" maxOccurs="unbounded">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="ValidSources" minOccurs="0" maxOccurs ="1">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="SourceType" type="DestroySourceType" minOccurs="1" maxOccurs ="unbounded"/>
                           </xs:sequence>
                        </xs:complexType>
                     </xs:element>
                     <xs:element name="OnDestroy" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="Trauma" type="TraumaDatas" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="SpawnFromPool" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
                           </xs:sequence>
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Id" type="xs:token" use="required"/>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:simpleType name="DestroySourceType" final="restriction">
      <xs:restriction base="xs:string">
         <xs:enumeration value="ATTACK"/>
         <xs:enumeration value="ROLL"/>
         <xs:enumeration value="FALL"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:complexType name="TraumaDatas">
      <xs:attribute name="X" type="xs:float" use="required"/>
      <xs:attribute name="Y" type="xs:float" use="required"/>
      <xs:attribute name="AddType" type="TraumaAddType" use="required"/>
      <xs:attribute name="ShakeId" type="xs:token" use="optional"/>
   </xs:complexType>

   <xs:simpleType name="TraumaAddType" final="restriction">
      <xs:restriction base="xs:string">
         <xs:enumeration value="ADDITIVE"/>
         <xs:enumeration value="OVERRIDE"/>
      </xs:restriction>
   </xs:simpleType>

</xs:schema>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/DestroyablesDatas.xml
<?xml version="1.0" encoding="utf-8" ?>
<DestroyablesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DestroyablesDatas.xsd">

   <DestroyableDatas Id="Crate">
      <ValidSources>
         <SourceType>ATTACK</SourceType>
         <SourceType>ROLL</SourceType>
         <SourceType>FALL</SourceType>
      </ValidSources>
      <OnDestroy>
         <Loot>
            <Value>3</Value>
            <Chance>0.33</Chance>
         </Loot>
         <Trauma X="0.3" Y ="0.3" AddType="ADDITIVE" ShakeId="Small"/>
         <SpawnFromPool>DoubleJump_Puff</SpawnFromPool>
         <SpawnFromPool>Crate_Particles_00</SpawnFromPool>
         <SpawnFromPool>Crate_Particles_01</SpawnFromPool>
         <SpawnFromPool>Crate_Particles_02</SpawnFromPool>
      </OnDestroy>
   </DestroyableDatas>

   <DestroyableDatas Id="Sign">
      <ValidSources>
         <SourceType>ATTACK</SourceType>
      </ValidSources>
      <OnDestroy>
         <Trauma X="0.25" Y ="0.25" AddType="ADDITIVE" ShakeId="Medium"/>
         <SpawnFromPool>Sign_Particles_00</SpawnFromPool>
         <SpawnFromPool>Sign_Particles_01</SpawnFromPool>
      </OnDestroy>
   </DestroyableDatas>

   <DestroyableDatas Id="Skull">
      <ValidSources>
         <SourceType>ATTACK</SourceType>
         <SourceType>ROLL</SourceType>
         <SourceType>FALL</SourceType>
      </ValidSources>
      <OnDestroy>
         <Loot>
            <Value>2</Value>
            <Chance>0.1</Chance>
         </Loot>
         <Trauma X="0.25" Y ="0.25" AddType="ADDITIVE" ShakeId="Small"/>
         <SpawnFromPool>DoubleJump_Puff</SpawnFromPool>
         <SpawnFromPool>Skull_Particles_00</SpawnFromPool>
         <SpawnFromPool>Skull_Particles_01</SpawnFromPool>
      </OnDestroy>
   </DestroyableDatas>

</DestroyablesDatas>
