=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/TriggerablesDatas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

   <xs:include schemaLocation="SharedDatas.xsd"/>

   <xs:element name="TriggerablesDatas">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="TriggerableDatas" minOccurs="0" maxOccurs="unbounded">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="ValidSources" minOccurs="0" maxOccurs ="1">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="SourceType" type="TriggerSourceType" minOccurs="1" maxOccurs ="unbounded"/>
                           </xs:sequence>
                        </xs:complexType>
                     </xs:element>
                     <xs:element name="MaxTriggersCount" type="xs:positiveInteger" minOccurs="0" maxOccurs="1"/>
                     <xs:element name="OnTrigger" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="Loot" type="LootDatas" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="Trauma" type="TraumaDatas" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="SpawnFromPool" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
                              <xs:element name="AnimatorTrigger" type="xs:token" minOccurs="0" maxOccurs="1"/>
                           </xs:sequence>
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Id" type="xs:token" use="required"/>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:simpleType name="TriggerSourceType" final="restriction">
      <xs:restriction base="xs:string">
         <xs:enumeration value="ATTACK"/>
         <xs:enumeration value="ROLL"/>
         <xs:enumeration value="FALL"/>
      </xs:restriction>
   </xs:simpleType>

</xs:schema>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/TriggerablesDatas.xml
<?xml version="1.0" encoding="utf-8" ?>
<TriggerablesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TriggerablesDatas.xsd">

   <TriggerableDatas Id="Crate">
      <ValidSources>
         <SourceType>ATTACK</SourceType>
         <SourceType>ROLL</SourceType>
         <SourceType>FALL</SourceType>
      </ValidSources>
      <MaxTriggersCount>1</MaxTriggersCount>
      <OnTrigger>
         <Loot>
            <Value>3</Value>
            <Chance>0.33</Chance>
         </Loot>
         <Trauma X="0.3" Y ="0.3" AddType="ADDITIVE" ShakeId="Small"/>
         <SpawnFromPool>DoubleJump_Puff</SpawnFromPool>
         <SpawnFromPool>Crate_Particles_00</SpawnFromPool>
         <SpawnFromPool>Crate_Particles_01</SpawnFromPool>
         <SpawnFromPool>Crate_Particles_02</SpawnFromPool>
      </OnTrigger>
   </TriggerableDatas>

   <TriggerableDatas Id="CrateWithGold">
      <ValidSources>
         <SourceType>ATTACK</SourceType>
         <SourceType>ROLL</SourceType>
         <SourceType>FALL</SourceType>
      </ValidSources>
      <MaxTriggersCount>1</MaxTriggersCount>
      <OnTrigger>
         <Loot>
            <Value>3</Value>
            <Chance>1</Chance>
         </Loot>
         <Trauma X="0.3" Y ="0.3" AddType="ADDITIVE" ShakeId="Small"/>
         <SpawnFromPool>DoubleJump_Puff</SpawnFromPool>
         <SpawnFromPool>Crate_Particles_00</SpawnFromPool>
         <SpawnFromPool>Crate_Particles_01</SpawnFromPool>
         <SpawnFromPool>Crate_Particles_02</SpawnFromPool>
      </OnTrigger>
   </TriggerableDatas>

   <TriggerableDatas Id="CrateZeroGold">
      <ValidSources>
         <SourceType>ATTACK</SourceType>
         <SourceType>ROLL</SourceType>
         <SourceType>FALL</SourceType>
      </ValidSources>
      <MaxTriggersCount>1</MaxTriggersCount>
      <OnTrigger>
         <Loot>
            <Value>0</Value>
            <Chance>0</Chance>
         </Loot>
         <Trauma X="0.3" Y ="0.3" AddType="ADDITIVE" ShakeId="Small"/>
         <SpawnFromPool>DoubleJump_Puff</SpawnFromPool>
         <SpawnFromPool>Crate_Particles_00</SpawnFromPool>
         <SpawnFromPool>Crate_Particles_01</SpawnFromPool>
         <SpawnFromPool>Crate_Particles_02</SpawnFromPool>
      </OnTrigger>
   </TriggerableDatas>

   <TriggerableDatas Id="Sign">
      <ValidSources>
         <SourceType>ATTACK</SourceType>
      </ValidSources>
      <MaxTriggersCount>1</MaxTriggersCount>
      <OnTrigger>
         <Trauma X="0.25" Y ="0.25" AddType="ADDITIVE" ShakeId="Medium"/>
         <SpawnFromPool>Sign_Particles_00</SpawnFromPool>
         <SpawnFromPool>Sign_Particles_01</SpawnFromPool>
      </OnTrigger>
   </TriggerableDatas>

   <TriggerableDatas Id="Skull">
      <ValidSources>
         <SourceType>ATTACK</SourceType>
         <SourceType>ROLL</SourceType>
         <SourceType>FALL</SourceType>
      </ValidSources>
      <MaxTriggersCount>1</MaxTriggersCount>
      <OnTrigger>
         <Loot>
            <Value>2</Value>
            <Chance>0.1</Chance>
         </Loot>
         <Trauma X="0.25" Y ="0.25" AddType="ADDITIVE" ShakeId="Small"/>
         <SpawnFromPool>DoubleJump_Puff</SpawnFromPool>
         <SpawnFromPool>Skull_Particles_00</SpawnFromPool>
         <SpawnFromPool>Skull_Particles_01</SpawnFromPool>
      </OnTrigger>
   </TriggerableDatas>

   <TriggerableDatas Id="Lever">
      <ValidSources>
         <SourceType>ATTACK</SourceType>
      </ValidSources>
      <OnTrigger>
         <Trauma X="0.25" Y ="0.25" AddType="ADDITIVE" ShakeId="Medium"/>
         <SpawnFromPool>Hit</SpawnFromPool>
         <SpawnFromPool>Land_Puff</SpawnFromPool>
      </OnTrigger>
   </TriggerableDatas>

</TriggerablesDatas>
