=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesDatas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

   <xs:include schemaLocation="../SharedDatas.xsd"/>

   <xs:element name="DialoguesDatas">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="DialogueDatas" type="DialogueDatas" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="SentenceDatas"  type="SentenceDatas" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:complexType name="DialogueDatas">
      <xs:sequence>
         <xs:element name="HidePortraitBox" minOccurs="0" maxOccurs="1"/>
         <xs:element name="InvertPortraitsAnchors" minOccurs="0" maxOccurs="1"/>
         <xs:element name="Sequence" minOccurs="1" maxOccurs="1">
            <xs:complexType>
               <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:element name="Sentence">
                     <xs:complexType>
                        <xs:sequence>
                           <!--Override anchor, override speaker name, etc.-->
                        </xs:sequence>
                        <xs:attribute name="Id" type="xs:token" use="required"/>
                     </xs:complexType>
                  </xs:element>
                  <xs:element name="Pause">
                     <xs:complexType>
                        <xs:sequence>
                        </xs:sequence>
                        <!--Hide panel or not (attribute) ?-->
                        <xs:attribute name="Dur" type="xs:float" use="required"/>
                     </xs:complexType>
                  </xs:element>
                  <xs:element name="AddItem" type="ItemDropDatas"/>
                  <xs:element name="RemoveItem" type="ItemDropDatas"/>
                  <xs:element name="SellItem">
                     <xs:complexType>
                        <xs:sequence>
                           <xs:element name="CustomLocalizationId" type="xs:token" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                        <xs:attribute name="Id" type="xs:token" use="required"/>
                        <xs:attribute name="Price" type="xs:nonNegativeInteger" use="required" default="0"/>
                        <xs:attribute name="Quantity" type="xs:nonNegativeInteger" use="optional" default="1"/>
                     </xs:complexType>
                  </xs:element>
               </xs:choice>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="Id" type="xs:token" use="required"/>
   </xs:complexType>

   <xs:complexType name="SentenceDatas">
      <xs:sequence>
         <xs:element name="Speaker" minOccurs="0" maxOccurs="1">
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="OverrideDisplayName" type="xs:token" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="HidePortraitBox" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="HideSpeakerName" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="OverridePortraitId" type="xs:token" minOccurs="0" maxOccurs="1"/>
               </xs:sequence>
               <xs:attribute name="Id" type="xs:token" use="required"/>
            </xs:complexType>
         </xs:element>
         <xs:element name="OverridePortraitAnchor" type="PortraitAnchor" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="Id" type="xs:token" use="required"/>
   </xs:complexType>

   <xs:simpleType name="PortraitAnchor" final="restriction">
      <xs:restriction base="xs:string">
         <xs:enumeration value="TOP_LEFT"/>
         <xs:enumeration value="TOP_RIGHT"/>
      </xs:restriction>
   </xs:simpleType>

</xs:schema>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesDatas_Meric.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesDatas.xsd">

   <!-- ███████████ -->
   <!--  DIALOGUES  -->
   <!-- ███████████ -->

   <DialogueDatas Id="Meric_Greeting">
      <Sequence>
         <Sentence Id="Meric_Greeting_00"/>
         <Sentence Id="Meric_Greeting_01"/>
         <Sentence Id="Meric_Greeting_02"/>
         <Pause Dur="0.5"/>
         <Sentence Id="Meric_Greeting_03"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="Meric_LoopingSentence">
      <Sequence>
         <Sentence Id="Meric_LoopingSentence_00"/>
      </Sequence>
   </DialogueDatas>

   
   <!-- ███████████ -->
   <!--  SENTENCES  -->
   <!-- ███████████ -->

   <SentenceDatas Id="Meric_Greeting_00">
      <Speaker Id="Meric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Meric_Greeting_01">
      <Speaker Id="Meric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Meric_Greeting_02">
      <Speaker Id="Meric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Meric_Greeting_03">
      <Speaker Id="Meric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Meric_LoopingSentence_00">
      <Speaker Id="Meric">
      </Speaker>
   </SentenceDatas>
   
</DialoguesDatas>

=== sixrobin/Febilis/Assets/Datafiles/Dialogues/DialoguesDatas_Test.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesDatas.xsd">

   <DialogueDatas Id="NPCDial_00">
      <Sequence>
         <Sentence Id="NPCDial_00_Sentence_00"/>
         <Pause Dur="0.5"/>
         <Sentence Id="NPCDial_00_Sentence_01"/>
         <AddItem Id="Test"/>
         <Sentence Id="NPCDial_00_Sentence_02"/>
         <Sentence Id="NPCDial_00_Sentence_NameReveal"/>
         <Sentence Id="NPCDial_00_Sentence_03"/>
         <Pause Dur="0.5"/>
         <Sentence Id="NPC_Ellipsis"/>
         <Sentence Id="NPCDial_00_Sentence_04"/>
      </Sequence>
   </DialogueDatas>

   <SentenceDatas Id="NPCDial_00_Sentence_00">
      <Speaker Id="SpeakerPlaceholder">
         <OverrideDisplayName>???</OverrideDisplayName>
         <OverridePortraitId>Unknown</OverridePortraitId>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="NPCDial_00_Sentence_01">
      <Speaker Id="SpeakerPlaceholder">
         <OverrideDisplayName>???</OverrideDisplayName>
         <OverridePortraitId>Unknown</OverridePortraitId>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="NPCDial_00_Sentence_02">
      <Speaker Id="Templar"/>
   </SentenceDatas>

   <SentenceDatas Id="NPCDial_00_Sentence_NameReveal">
      <Speaker Id="SpeakerPlaceholder"/>
   </SentenceDatas>

   <SentenceDatas Id="NPCDial_00_Sentence_03">
      <Speaker Id="SpeakerPlaceholder"/>
   </SentenceDatas>

   <SentenceDatas Id="NPCDial_00_Sentence_04">
      <Speaker Id="SpeakerPlaceholder"/>
   </SentenceDatas>

   <SentenceDatas Id="NPC_Ellipsis">
      <Speaker Id="SpeakerPlaceholder">
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>
   
</DialoguesDatas>

=== sixrobin/Febilis/Assets/Datafiles/Dialogues/DialoguesDatas_StoneSigns.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesDatas.xsd">

   <DialogueDatas Id="StoneSign_00">
      <HidePortraitBox/>
      <Sequence>
         <Sentence Id="StoneSign_00_Sentence_00"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="StoneSign_01">
      <HidePortraitBox/>
      <Sequence>
         <Sentence Id="StoneSign_01_Sentence_00"/>
         <Sentence Id="StoneSign_01_Sentence_01"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="StoneSign_02">
      <HidePortraitBox/>
      <Sequence>
         <Sentence Id="StoneSign_02_Sentence_00"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="StoneSign_CatacombsEntry">
      <HidePortraitBox/>
      <Sequence>
         <Sentence Id="StoneSign_CatacombsEntry_Sentence_00"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="StoneSign_RatKing">
      <!--<HidePortraitBox/>-->
      <Sequence>
         <Sentence Id="StoneSign_RatKing_Sentence_00"/>
         <Sentence Id="StoneSign_RatKing_Sentence_01"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="StoneSign_SecretWallHint">
      <!--<HidePortraitBox/>-->
      <Sequence>
         <Sentence Id="StoneSign_SecretWallHint_00"/>
         <Sentence Id="StoneSign_SecretWallHint_01"/>
         <Pause Dur="0.5"/>
         <Sentence Id="StoneSign_SecretWallHint_02"/>
      </Sequence>
   </DialogueDatas>
   

   <SentenceDatas Id="StoneSign_00_Sentence_00">
      <Speaker Id="Templar">
         <HidePortraitBox/>
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_01_Sentence_00">
      <Speaker Id="Templar">
         <HidePortraitBox/>
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_01_Sentence_01">
      <Speaker Id="Templar">
         <HidePortraitBox/>
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_02_Sentence_00">
      <Speaker Id="Templar">
         <HidePortraitBox/>
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_CatacombsEntry_Sentence_00">
      <Speaker Id="Templar">
         <HidePortraitBox/>
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_RatKing_Sentence_00">
      <Speaker Id="Templar">
         <HidePortraitBox/>
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_RatKing_Sentence_01">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_SecretWallHint_00">
      <Speaker Id="Templar">
         <HidePortraitBox/>
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_SecretWallHint_01">
      <Speaker Id="Templar">
         <HidePortraitBox/>
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_SecretWallHint_02">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>
   
</DialoguesDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesDatas_Generics.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesDatas.xsd">

   <DialogueDatas Id="LockedDoor">
      <Sequence>
         <Sentence Id="LockedDoor_Sentence_00"/>
      </Sequence>
   </DialogueDatas>

   <SentenceDatas Id="LockedDoor_Sentence_00">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
      <Value>It's locked.</Value>
   </SentenceDatas>
   
</DialoguesDatas>
