=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesStructuresDatas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

   <xs:include schemaLocation="../SharedDatas.xsd"/>

   <xs:element name="DialoguesStructuresDatas">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="DialoguesStructureDatas" type="DialoguesStructureDatas" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:complexType name="DialoguesStructureDatas">
      <xs:sequence>
         <xs:element name="SoldItems" minOccurs="0" maxOccurs="1">
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="ItemId" minOccurs="1" maxOccurs="unbounded"/>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
         <xs:element name="Dialogue" type="StructureDialogueDatas" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="Id" type="xs:token" use="required"/>
   </xs:complexType>

   <xs:complexType name="StructureDialogueDatas">
      <xs:sequence>
         <xs:element name="Conditions" minOccurs="0" maxOccurs="1">
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="DialogueNeverDone" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
                  <xs:element name="PlayerHasItem" minOccurs="0" maxOccurs="unbounded">
                     <xs:complexType>
                        <xs:attribute name="Id" type="xs:token" use="required"/>
                        <xs:attribute name="MinQuantity" type="xs:nonNegativeInteger" use="optional"/>
                     </xs:complexType>
                  </xs:element>
                  <xs:element name="PlayerDoesntHaveItem" minOccurs="0" maxOccurs="unbounded">
                     <xs:complexType>
                        <xs:attribute name="Id" type="xs:token" use="required"/>
                     </xs:complexType>
                  </xs:element>
                  <xs:element name="BoardDiscovered" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
                  <xs:element name="ZoneDiscovered" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
                  <xs:element name="ItemUnsold" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="Id" type="xs:token" use="required"/>
   </xs:complexType>

</xs:schema>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesStructuresDatas_Godric.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesStructuresDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesStructuresDatas.xsd">

   <DialoguesStructureDatas Id="Godric">

      <Dialogue Id="Godric_Greeting_Ring">
         <Conditions>
            <DialogueNeverDone>Godric_Greeting</DialogueNeverDone>
            <DialogueNeverDone>Godric_Greeting_Ring</DialogueNeverDone>
            <PlayerHasItem Id="Ring_Godric" MinQuantity="1"/>
         </Conditions>
      </Dialogue>

      <Dialogue Id="Godric_Greeting">
         <Conditions>
            <DialogueNeverDone>Godric_Greeting</DialogueNeverDone>
            <DialogueNeverDone>Godric_Greeting_Ring</DialogueNeverDone>
         </Conditions>
      </Dialogue>

      <Dialogue Id="Godric_WaitingRing">
         <Conditions>
            <DialogueNeverDone>Godric_RetrieveRing</DialogueNeverDone>
            <DialogueNeverDone>Godric_Greeting_Ring</DialogueNeverDone>
            <PlayerDoesntHaveItem Id="Ring_Godric"/>
         </Conditions>
      </Dialogue>

      <Dialogue Id="Godric_RetrieveRing">
         <Conditions>
            <PlayerHasItem Id="Ring_Godric" MinQuantity="1"/>
         </Conditions>
      </Dialogue>

      <Dialogue Id="Godric_PostRetrieveRing">
      </Dialogue>
      
   </DialoguesStructureDatas>

</DialoguesStructuresDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesStructuresDatas_OfferingStone.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesStructuresDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesStructuresDatas.xsd">

   <DialoguesStructureDatas Id="OfferingStone">

      <SoldItems>
         <ItemId>GodsEmblem</ItemId>
      </SoldItems>
      
      <Dialogue Id="OfferingStone_ItemLeft">
         <Conditions>
            <!-- TODO: Item to sold left. -->
         </Conditions>
      </Dialogue>

      <Dialogue Id="OfferingStone_NoItemLeft">
         <Conditions>
         </Conditions>
      </Dialogue>
      
   </DialoguesStructureDatas>

</DialoguesStructuresDatas>
