=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesDatas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

   <xs:include schemaLocation="../SharedDatas.xsd"/>

   <xs:element name="DialoguesDatas">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="DialogueDatas" type="DialogueDatas" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="SentenceDatas"  type="SentenceDatas" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:complexType name="DialogueDatas">
      <xs:sequence>
         <xs:element name="HidePortraitBox" minOccurs="0" maxOccurs="1"/>
         <xs:element name="InvertPortraitsAnchors" minOccurs="0" maxOccurs="1"/>
         <xs:element name="Sequence" minOccurs="1" maxOccurs="1">
            <xs:complexType>
               <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:element name="Sentence">
                     <xs:complexType>
                        <xs:sequence>
                           <!--Override anchor, override speaker name, etc.-->
                        </xs:sequence>
                        <xs:attribute name="Id" type="xs:token" use="required"/>
                     </xs:complexType>
                  </xs:element>
                  <xs:element name="Pause">
                     <xs:complexType>
                        <xs:sequence>
                        </xs:sequence>
                        <!--Hide panel or not (attribute) ?-->
                        <xs:attribute name="Dur" type="xs:float" use="required"/>
                     </xs:complexType>
                  </xs:element>
                  <xs:element name="AddItem" type="ItemDropDatas"/>
                  <xs:element name="RemoveItem" type="ItemDropDatas"/>
                  <xs:element name="SellItem">
                     <xs:complexType>
                        <xs:sequence>
                           <xs:element name="CustomLocalizationId" type="xs:token" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                        <xs:attribute name="Id" type="xs:token" use="required"/>
                        <xs:attribute name="Price" type="xs:nonNegativeInteger" use="required" default="0"/>
                        <xs:attribute name="Quantity" type="xs:nonNegativeInteger" use="optional" default="1"/>
                     </xs:complexType>
                  </xs:element>
               </xs:choice>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="Id" type="xs:token" use="required"/>
   </xs:complexType>

   <xs:complexType name="SentenceDatas">
      <xs:sequence>
         <xs:element name="Speaker" minOccurs="0" maxOccurs="1">
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="OverrideDisplayName" type="xs:token" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="HidePortraitBox" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="HideSpeakerName" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="OverridePortraitId" type="xs:token" minOccurs="0" maxOccurs="1"/>
               </xs:sequence>
               <xs:attribute name="Id" type="xs:token" use="required"/>
            </xs:complexType>
         </xs:element>
         <xs:element name="OverridePortraitAnchor" type="PortraitAnchor" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="Id" type="xs:token" use="required"/>
   </xs:complexType>

   <xs:simpleType name="PortraitAnchor" final="restriction">
      <xs:restriction base="xs:string">
         <xs:enumeration value="TOP_LEFT"/>
         <xs:enumeration value="TOP_RIGHT"/>
      </xs:restriction>
   </xs:simpleType>

</xs:schema>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesDatas_Twitter.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesDatas.xsd">

   <DialogueDatas Id="Twitter">
      <InvertPortraitsAnchors/>
      <Sequence>
         <!--<AddItem Id="Ring_00" Quantity="666"/>-->
         <!--<AddItem Id="Scroll"/>-->
         <Sentence Id="Twitter_00"/>
         <Pause Dur="0.5"/>
         <Sentence Id="Twitter_01"/>
         <Sentence Id="Twitter_02"/>
         <!--<RemoveItem Id="Ring_00" Quantity="333"/>-->
         <!--<RemoveItem Id="Ring_01" />-->
         <Sentence Id="Twitter_03"/>
         <Sentence Id="Twitter_04"/>
         <Pause Dur="0.5"/>
         <Sentence Id="Twitter_05"/>
      </Sequence>
   </DialogueDatas>

   <SentenceDatas Id="Twitter_00">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
      <Value>Hey there. Who are you ?</Value>
   </SentenceDatas>

   <SentenceDatas Id="Twitter_01">
      <Speaker Id="SpeakerPlaceholder">
         <HideSpeakerName/>
         <OverridePortraitId>Unknown</OverridePortraitId>
      </Speaker>
      <Value>[pause=0.3].[pause=0.3].[pause=0.3].</Value>
   </SentenceDatas>

   <SentenceDatas Id="Twitter_02">
      <Speaker Id="SpeakerPlaceholder">
         <OverrideDisplayName>Bob</OverrideDisplayName>
         <HideSpeakerName/>
      </Speaker>
      <Value>I'm Bob.</Value>
   </SentenceDatas>

   <SentenceDatas Id="Twitter_03">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
      <Value>[pause=0.1].[pause=0.1].[pause=0.1].</Value>
   </SentenceDatas>

   <SentenceDatas Id="Twitter_04">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
      <Value>I'm getting short on imagination for those gifs...</Value>
   </SentenceDatas>

   <SentenceDatas Id="Twitter_05">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
      <Value>But hopefully, you can see the dialogue system progress ! :D</Value>
   </SentenceDatas>

</DialoguesDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesDatas_StoneSigns.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesDatas.xsd">

   <DialogueDatas Id="StoneSign_00">
      <HidePortraitBox/>
      <Sequence>
         <Sentence Id="StoneSign_00_Sentence_00"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="StoneSign_01">
      <HidePortraitBox/>
      <Sequence>
         <Sentence Id="StoneSign_01_Sentence_00"/>
         <Sentence Id="StoneSign_01_Sentence_01"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="StoneSign_02">
      <HidePortraitBox/>
      <Sequence>
         <Sentence Id="StoneSign_02_Sentence_00"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="StoneSign_CatacombsEntry">
      <HidePortraitBox/>
      <Sequence>
         <Sentence Id="StoneSign_CatacombsEntry_Sentence_00"/>
      </Sequence>
   </DialogueDatas>


   <SentenceDatas Id="StoneSign_00_Sentence_00">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
      <Value>"This is the place of the heretics, who may be forgotten, and so should their names."</Value>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_01_Sentence_00">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
      <Value>"This is the place of the ones who built the catacombs."</Value>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_01_Sentence_01">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
      <Value>"Once fated to death sentence, they redeemed themselves by putting up this place."</Value>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_02_Sentence_00">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
      <Value>"Place of the commoners."</Value>
   </SentenceDatas>

   <SentenceDatas Id="StoneSign_CatacombsEntry_Sentence_00">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
      <Value>"Here lie the dead, and those who got cursed by Febilis."</Value>
   </SentenceDatas>
   
</DialoguesDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesDatas_Peregrin.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesDatas.xsd">

   <!-- ███████████ -->
   <!--  DIALOGUES  -->
   <!-- ███████████ -->

   <DialogueDatas Id="Peregrin_Greeting">
      <Sequence>
         <Sentence Id="Peregrin_Greeting_00"/>
         <Sentence Id="Peregrin_Greeting_01"/>
         <Sentence Id="Peregrin_Greeting_02"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="Peregrin_LoopingSentence">
      <Sequence>
         <Sentence Id="Peregrin_LoopingSentence_00"/>
      </Sequence>
   </DialogueDatas>

   
   <!-- ███████████ -->
   <!--  SENTENCES  -->
   <!-- ███████████ -->

   <SentenceDatas Id="Peregrin_Greeting_00">
      <Speaker Id="Peregrin">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Peregrin_Greeting_01">
      <Speaker Id="Peregrin">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Peregrin_Greeting_02">
      <Speaker Id="Peregrin">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Peregrin_LoopingSentence_00">
      <Speaker Id="Peregrin">
      </Speaker>
   </SentenceDatas>
   
</DialoguesDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesDatas_Test.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesDatas.xsd">

   <DialogueDatas Id="NPCDial_00">
      <Sentence Id="NPCDial_00_Sentence_00"/>
      <Pause Dur="0.5"/>
      <Sentence Id="NPCDial_00_Sentence_01"/>
      <Sentence Id="NPCDial_00_Sentence_02"/>
      <Sentence Id="NPCDial_00_Sentence_NameReveal"/>
      <Sentence Id="NPCDial_00_Sentence_03"/>
      <Pause Dur="0.5"/>
      <Sentence Id="NPC_Ellipsis"/>
      <Sentence Id="NPCDial_00_Sentence_04"/>
   </DialogueDatas>

   <SentenceDatas Id="NPCDial_00_Sentence_00">
      <Speaker Id="SpeakerPlaceholder">
         <OverrideDisplayName>???</OverrideDisplayName>
         <OverridePortraitId>Unknown</OverridePortraitId>
      </Speaker>
      <Value>Hi there, what are you doing here ?</Value>
   </SentenceDatas>

   <SentenceDatas Id="NPCDial_00_Sentence_01">
      <Speaker Id="SpeakerPlaceholder">
         <OverrideDisplayName>???</OverrideDisplayName>
         <OverridePortraitId>Unknown</OverridePortraitId>
      </Speaker>
      <Value>Ah, I see...[pause=3] Looking for answers ?</Value>
   </SentenceDatas>

   <SentenceDatas Id="NPCDial_00_Sentence_02">
      <Speaker Id="Templar"/>
      <Value>What do you know about this place ? [pause=1]It all looks... [pause=0.8]unreal.</Value>
   </SentenceDatas>

   <SentenceDatas Id="NPCDial_00_Sentence_NameReveal">
      <Speaker Id="SpeakerPlaceholder"/>
      <Value>Now you can see my portrait.</Value>
   </SentenceDatas>

   <SentenceDatas Id="NPCDial_00_Sentence_03">
      <Speaker Id="SpeakerPlaceholder"/>
      <Value>Unreal, uh ? Maybe it is ! Ha, ah, ah !</Value>
   </SentenceDatas>

   <SentenceDatas Id="NPCDial_00_Sentence_04">
      <Speaker Id="SpeakerPlaceholder"/>
      <Value>Go away.</Value>
   </SentenceDatas>

   <SentenceDatas Id="NPC_Ellipsis">
      <Speaker Id="SpeakerPlaceholder">
         <HideSpeakerName/>
      </Speaker>
      <Value>[pause=0.3].[pause=0.3].[pause=0.3].</Value>
   </SentenceDatas>
   
</DialoguesDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesDatas_NPC01.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesDatas.xsd">

   <DialogueDatas Id="NPC01_Greeting">
      <InvertPortraitsAnchors/>
      <Sequence>
         <Sentence Id="NPC01_Greeting_00"/>
         <Pause Dur="0.5"/>
         <Sentence Id="NPC01_Greeting_01"/>
         <Sentence Id="NPC01_Greeting_02"/>
         <Sentence Id="NPC01_Greeting_03"/>
         <Sentence Id="NPC01_Greeting_04"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="NPC01_PostGreeting">
      <InvertPortraitsAnchors/>
      <Sequence>
         <Sentence Id="NPC01_PostGreeting_00"/>
      </Sequence>
   </DialogueDatas>

   
   <SentenceDatas Id="NPC01_Greeting_00">
      <Speaker Id="NPC01">
         <OverrideDisplayName>???</OverrideDisplayName>
<!--         <OverridePortraitId>Unknown</OverridePortraitId>-->
      </Speaker>
      <Value>Hello, stranger...</Value>
   </SentenceDatas>

   <SentenceDatas Id="NPC01_Greeting_01">
      <Speaker Id="NPC01">
         <OverrideDisplayName>???</OverrideDisplayName>
<!--         <OverridePortraitId>Unknown</OverridePortraitId>-->
      </Speaker>
      <Value>Interesting.[pause=0.5].[pause=0.5].[pause=0.5] you're from the pale militia. Long time I didn't see this armor.</Value>
   </SentenceDatas>

   <SentenceDatas Id="NPC01_Greeting_02">
      <Speaker Id="NPC01">
         <OverrideDisplayName>???</OverrideDisplayName>
<!--         <OverridePortraitId>Unknown</OverridePortraitId>-->
      </Speaker>
      <Value>I suppose you're heading to the village to inspect all this crazy mess.</Value>
   </SentenceDatas>

   <SentenceDatas Id="NPC01_Greeting_03">
      <Speaker Id="NPC01">
         <OverrideDisplayName>???</OverrideDisplayName>
<!--         <OverridePortraitId>Unknown</OverridePortraitId>-->
      </Speaker>
      <Value>Quick advice, even with your grade, stay low and mind your own business.</Value>
   </SentenceDatas>

   <SentenceDatas Id="NPC01_Greeting_04">
      <Speaker Id="NPC01">
         <OverrideDisplayName>???</OverrideDisplayName>
<!--         <OverridePortraitId>Unknown</OverridePortraitId>-->
      </Speaker>
      <Value>Those are some strange times we're in...</Value>
   </SentenceDatas>

   
   <SentenceDatas Id="NPC01_PostGreeting_00">
      <Speaker Id="NPC01">
         <OverrideDisplayName>???</OverrideDisplayName>
<!--         <OverridePortraitId>Unknown</OverridePortraitId>-->
      </Speaker>
      <Value>Do not forget, stay low and mind your own business.</Value>
   </SentenceDatas>

</DialoguesDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesDatas_OfferingStone.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesDatas.xsd">

   <!-- ███████████ -->
   <!--  DIALOGUES  -->
   <!-- ███████████ -->

   <DialogueDatas Id="OfferingStone_ItemLeft">
      <Sequence>
         <Sentence Id="OfferingStone_ItemLeft_00"/>
         <Sentence Id="OfferingStone_ItemLeft_01"/>
         <SellItem Id="GodsEmblem" Price="150">
            <CustomLocalizationId>OfferingStone_GodsEmblem</CustomLocalizationId>
         </SellItem>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="OfferingStone_NoItemLeft">
      <Sequence>
         <Sentence Id="OfferingStone_NoItemLeft_00"/>
      </Sequence>
   </DialogueDatas>

   
   <!-- ███████████ -->
   <!--  SENTENCES  -->
   <!-- ███████████ -->

   <SentenceDatas Id="OfferingStone_ItemLeft_00">
      <Speaker Id="OfferingStone">
         <HidePortraitBox/>
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="OfferingStone_ItemLeft_01">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>
   

   <SentenceDatas Id="OfferingStone_NoItemLeft_00">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
   </SentenceDatas>
   
</DialoguesDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesDatas_Godric.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesDatas.xsd">

   <!-- ███████████ -->
   <!--  DIALOGUES  -->
   <!-- ███████████ -->

   <DialogueDatas Id="Godric_Greeting">
      <Sequence>
         <Sentence Id="Godric_Greeting_00"/>
         <Sentence Id="Godric_Greeting_01"/>
         <Sentence Id="Godric_Greeting_02"/>
         <Sentence Id="Godric_Greeting_03"/>
         <Sentence Id="Godric_Greeting_04"/>
         <AddItem Id="Key_Godric_House"/>
         <Sentence Id="Godric_Greeting_05"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="Godric_Greeting_Ring">
      <Sequence>
         <Sentence Id="Godric_Greeting_Ring_00"/>
         <Sentence Id="Godric_Greeting_Ring_01"/>
         <Sentence Id="Godric_Greeting_Ring_02"/>
         <Sentence Id="Godric_Greeting_Ring_03"/>
         <RemoveItem Id="Ring_Godric"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="Godric_WaitingRing">
      <Sequence>
         <Sentence Id="Godric_WaitingRing_00"/>
         <Sentence Id="Godric_WaitingRing_01"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="Godric_RetrieveRing">
      <Sequence>
         <Sentence Id="Godric_RetrieveRing_00"/>
         <RemoveItem Id="Ring_Godric"/>
         <Sentence Id="Godric_RetrieveRing_01"/>
         <Sentence Id="Godric_RetrieveRing_02"/>
         <Sentence Id="Godric_RetrieveRing_03"/>
         <Sentence Id="Godric_RetrieveRing_04"/>
         <AddItem Id="Potion"/>
      </Sequence>
   </DialogueDatas>

   <DialogueDatas Id="Godric_PostRetrieveRing">
      <Sequence>
         <Sentence Id="Godric_PostRetrieveRing_00"/>
      </Sequence>
   </DialogueDatas>

   
   <!-- ███████████ -->
   <!--  SENTENCES  -->
   <!-- ███████████ -->

   <SentenceDatas Id="Godric_Greeting_00">
      <Speaker Id="Godric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Godric_Greeting_01">
      <Speaker Id="Godric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Godric_Greeting_02">
      <Speaker Id="Godric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Godric_Greeting_03">
      <Speaker Id="Godric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Godric_Greeting_04">
      <Speaker Id="Godric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Godric_Greeting_05">
      <Speaker Id="Godric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>


   <SentenceDatas Id="Godric_Greeting_Ring_00">
      <Speaker Id="Godric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Godric_Greeting_Ring_01">
      <Speaker Id="Godric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Godric_Greeting_Ring_02">
      <Speaker Id="Godric">
         <OverrideDisplayName>???</OverrideDisplayName>
      </Speaker>
   </SentenceDatas>

   <SentenceDatas Id="Godric_Greeting_Ring_03">
      <Speaker Id="Godric"/>
   </SentenceDatas>
   
   
   <SentenceDatas Id="Godric_WaitingRing_00">
      <Speaker Id="Godric"/>
   </SentenceDatas>

   <SentenceDatas Id="Godric_WaitingRing_01">
      <Speaker Id="Godric"/>
   </SentenceDatas>
   
   
   <SentenceDatas Id="Godric_RetrieveRing_00">
      <Speaker Id="Godric"/>
   </SentenceDatas>

   <SentenceDatas Id="Godric_RetrieveRing_01">
      <Speaker Id="Godric"/>
   </SentenceDatas>

   <SentenceDatas Id="Godric_RetrieveRing_02">
      <Speaker Id="Godric"/>
   </SentenceDatas>

   <SentenceDatas Id="Godric_RetrieveRing_03">
      <Speaker Id="Godric"/>
   </SentenceDatas>

   <SentenceDatas Id="Godric_RetrieveRing_04">
      <Speaker Id="Godric"/>
   </SentenceDatas>

   <SentenceDatas Id="Godric_PostRetrieveRing_00">
      <Speaker Id="Godric"/>
   </SentenceDatas>
   
</DialoguesDatas>

=== sixrobin/Febilis/SOURCES/TEMPLAR/Assets/Datafiles/Dialogues/DialoguesDatas_LennyStatue.xml
<?xml version="1.0" encoding="utf-8" ?>
<DialoguesDatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DialoguesDatas.xsd">

   <DialogueDatas Id="LennyStatue">
      <Sequence>
         <Sentence Id="LennyStatue_00"/>
         <Sentence Id="LennyStatue_01"/>
      </Sequence>
   </DialogueDatas>

   <SentenceDatas Id="LennyStatue_00">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
      <Unskippable/>
   </SentenceDatas>

   <SentenceDatas Id="LennyStatue_01">
      <Speaker Id="Templar">
         <HideSpeakerName/>
      </Speaker>
      <Unskippable/>
   </SentenceDatas>
   
</DialoguesDatas>
